export const Images = {
  userPic: require('../assets/userPic.png'),
  bell: require('../assets/bell.png'),
  home: require('../assets/home.png'),
  homeSelected: require('../assets/home96.png'),
  map: require('../assets/map.png'),
  mapSelected: require('../assets/map96.png'),
  heart: require('../assets/heart.png'),
  heartSelected: require('../assets/heart90.png'),
  profile: require('../assets/profile.png'),
  profileSelected: require('../assets/customer.png'),
  search: require('../assets/search.png'),
  heartNew: require('../assets/heartnew.png'),
  location: require('../assets/locations.png'),
  locations: require('../assets/location96.png'),
  filter: require('../assets/filter.png'),
  navigation: require('../assets/navigation.png'),
  marker: require('../assets/location96.png'),
  viewIcon: require('../assets/view.png'),
  hideIcon: require('../assets/hide.png'),
  star: require('../assets/star.png'),
  heartOutLine: require('../assets/heart32.png'),
  bookingOutLine: require('../assets/booking.png'),
  bookingRed: require('../assets/booking3.png'),
};
