<?php

/**
 * This file generated by 'sync-version.sh' script
 *
 * WARNING! DO NOT EDIT. All changes made in this file will be lost when running sync-version.sh
 */

if (! function_exists('app_version_string')) {
    function app_version_string()
    {
        return '9999.999.99-dev';
    }
}
